apiVersion: apps/v1
kind: Deployment
metadata:
name: dotnet-app
spec:
selector:
matchLabels:
app: dotnet-app
replicas: 3
template:
metadata:
labels:
app: dotnet-app
spec:
containers:
name: dotnet-app
image: nrt.ocir.io/nrcbpbtrtyz0/dotnetrepo:latest
imagePullPolicy: Always
ports:
- containerPort: 8080
resources:
requests:
#memory: "500Mi"
imagePullSecrets:
name: ocirsecret
restartPolicy: Always