apiVersion: v1
kind: Service
metadata:
  name: dotnet-app
  labels:
    app: dotnet-app
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: dotnet-app
